### PR TITLE
Just an upgrade to support Clojure 1.2.

### PR DESCRIPTION
**Pull request by technomancy**
pretty simple.

### CODE REVIEW

**Comment by weavejester** [comment]
If the document map being added to the search index has a key pointing to a numeric value, `(name value)` will except. We could use `(str value)`, but that might not work for keys that act like enumerations, e.g. `{:state :ready}`.

**Comment by technomancy** [comment]
Ah; I didn't realize it was used in the context of numerics. Rewrote my last commit so it just bundles as-str, which special-cases symbols and calls str otherwise.

**Comment by weavejester** [comment]
I'm not certain whether a number would ever be used, but I can imagine someone adding a document like:

```
{:name "Alice Carol", :age 29, :status :single}
```

And in which case I think I'd prefer it to be indexed without the user having to manually change all the values in the map to strings.

Anyway, your commit looks good, and I'll merge it in tonight!

**Comment by technomancy** [comment]
Makes plenty of sense.

Could we get it released on Clojars as an 0.1.1 release so Clojure 1.2 users will have an easier time using it?

**Comment by weavejester** [comment]
I just noticed that you removed the Clojure dependencies altogether from the project. Was there a reason for that?

**Comment by technomancy** [comment]
Yeah, I did that when I was still thinking I would make it backwards-compatible with older versions of Clojure. Now that we're requiring 1.2 I suppose it would be better to make that explicit in project.clj. So just an oversight.

**Comment by weavejester** [comment]
Okay, I've added a dependency to Clojure 1.2.1 in and released version 0.2.0.

**Comment by technomancy** [comment]
Woo hoo; thanks a bunch.

**Pull request merged**
